#mysql 5.7
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        # 主数据源
        master:
          url: jdbc:dm://GRP1?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: yellow_CAD
          password: ENC(VQYdzOJW9/8O/dkzbDMVhhPT2VjcSHlKCheXv42owF4=)
          driver-class-name: dm.jdbc.driver.DmDriver
        # 本地bim同步库
        bim_cad:
          url: jdbc:dm://GRP1?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: LTMF
          password: ENC(Mdv8vnuRGb9vCnT23Ny0DPUfY4Z8QPis8/2k1mbm7aw=)
          driver-class-name: dm.jdbc.driver.DmDriver
        # bim数据源
        bim_ltmf:
          url: jdbc:dm://172.24.72.71?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: LTMF
          password: ENC(kVI2dYC6wSD9yhboaqVUUdhjQ4siFqoi)
          driver-class-name: dm.jdbc.driver.DmDriver
    #druid连接池全局配置
    druid:
      #配置初始化连接数大小
      initial-size: 10
      # 最大连接数
      max-active: 50
      #最小连接数
      min-idle: 10
      #获取连接等待超时时间
      max-wait: 5000
      pool-prepared-statements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
      #StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        #可以增加访问账号密码【去掉注释就可以】
        login-username: admin
        login-password: 1323!Q@#EMSD%$^
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  redis:
    #数据库索引
    database: 1
    host: 172.20.88.27
    port: 17379
    password: ENC(4rGdou+NLhunGUsCC5t7zg/KZfcKXjxb)
    jedis:
      pool:
        #最大连接数
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 20
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

file:
  path: /storage/publicFile/data/
  certpath: /storage/publicFile/certinfo/

swagger:
  enable: true

#加密机签名相关
gmgz:
  #服务地址
  ipp: http://172.20.88.31:5000
  # 证书别名
  certAlias: sm2

#民防大系统跳转对接
mfPortal:
  oauth:
    ip: http://10.85.44.11/oauth
    tokenUrl: ${mfPortal.oauth.ip}/user/verifyToken
    clientId:
    aesKey: de6e1b402e7a00a3
