server:
  port: 11100
  servlet:
    context-path: /yellow

spring :
  application:
    name: yellow-api
  profiles :
    active : @spring.profiles.active@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 7200s
# Mybatis配置
mybatis-plus:
  type-aliases-package: com.yellow.api.model
  mapperLocations: classpath:mapper/*.xml,classpath:common/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置实体类字段注解)
      # 设置后，直接调用deleteById方法，会自动update deleteStatus=1
      # 设置后，mybatis plus的查询方法，会自动追加where deleteStatus=0 (未删除，如：selectById、 countById)
      # 设置后，mybatis plus的updateById方法，将不在update deleteStatus，即使set deleteStatus也没作用。可在xml中编写update语句，来解决
      logic-delete-field: isDel
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

yellow:
  auth:
    anon:
      - /v3/api-docs
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /swagger-resources/configuration/security
      - /webjars/**
      - /swagger-ui/**

      - /auth/captcha/**
      - /auth/login
      - /auth/logout

      - /test/**

      - /doc.html

      - /druid/**
    # cookie存活时间 默认4小时 目前用途：token
    cookie-max-age: 14400
  key:
    password: zhoukeystore
    secret: zhouhao
    alias: zhkey
    private-key-location: zh.keystore
    public-key-location: publickey.txt
log:
  path: E:\\logs